# 数据库配置（TiDB Cloud）
jdbc.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/psychology?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
jdbc.username=4LPL7JUrVDWLrQy.root
jdbc.password=RPBN3zcK519kp0ed
jdbc.driver=com.mysql.cj.jdbc.Driver
